repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      args: ["--markdown-linebreak-ext=md"]
      exclude: '\.md$'
    - id: end-of-file-fixer
      exclude: '\.md$'
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: '24.3.0'
  hooks:
    - id: black
      args: ["--preview", "--line-length=120"]
      language_version: python3.11
      exclude: ^scripts/ensure_asset_dirs\.py$

- repo: https://github.com/PyCQA/autoflake
  rev: v2.3.1
  hooks:
    - id: autoflake
      args: [
        --remove-all-unused-imports,
        --remove-unused-variables,
        --in-place
      ]

- repo: https://github.com/pycqa/isort
  rev: '5.13.2'
  hooks:
    - id: isort
      args: ["--profile", "black", "--line-length", "120"]

- repo: https://github.com/pycqa/flake8
  rev: '7.0.0'
  hooks:
    - id: flake8
      args: ["--max-line-length=120", "--extend-ignore=E203,F541,E711,E712,W293"]
      exclude: '(^.venv/|^venv/|^env/|^.*tokenizers.*.egg/)'

# Local hooks
- repo: local
  hooks:
    - id: ensure-asset-dirs
      name: Ensure asset directory structure
      entry: python scripts/ensure_asset_dirs.py
      language: system
      pass_filenames: false
      always_run: true
      files: ^assets/
    - id: skip-tokenizers-build
      name: Skip tokenizers build in pre-commit
      entry: python -c "import sys; sys.exit(0)"
      language: system
      files: ^.*tokenizers.*$
      pass_filenames: false
    - id: poetry-check
      name: Verify poetry.lock is up to date
      entry: poetry check --lock
      language: system
      pass_filenames: false
      files: ^pyproject.toml$
