name: Force Minimal V4 Artifact Upload Test

on:
  workflow_dispatch:
    inputs:
      diagnostic_version:
        description: 'Diagnostic version'
        required: true
        default: '0.1.0-force-v4-test'

permissions:
  contents: read
  actions: write

jobs:
  isolated-upload-test:
    name: Isolated V4 Artifact Upload
    runs-on: ubuntu-latest
    
    steps:
      - name: Initial Runner Diagnostics
        run: |
          echo "JOB_NAME: isolated-upload-test"
          echo "WORKFLOW_NAME: Force Minimal V4 Artifact Upload Test"
          echo "Runner OS: $(uname -a)"
          echo "Runner Version: ${{ runner.version }}"
          echo "Disk Space:"
          df -h
          echo "Network Ping (google.com):"
          ping -c 1 google.com || echo "Ping to google.com failed"
          echo "DNS Lookup (github.com):"
          nslookup github.com || echo "DNS lookup for github.com failed"
          echo "Date: $(date)"

      - name: Checkout Code (v4)
        uses: actions/checkout@v4

      - name: Create Dummy Artifact File
        run: |
          mkdir -p artifact_to_upload
          echo "Test content for v4 upload." > artifact_to_upload/test_file.txt
          ls -l artifact_to_upload

      - name: Upload Artifact using actions/upload-artifact@v4
        uses: actions/upload-artifact@v4
        with:
          name: minimal-v4-artifact
          path: artifact_to_upload/test_file.txt
          if-no-files-found: error
          retention-days: 1
          
      - name: Final Status
        run: echo "Artifact upload step completed or skipped."
