name: Package Test Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to test'
        required: true
        default: '0.1.0-test'

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.version }}
  cancel-in-progress: true

jobs:
  test-package:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements-tests.txt
          pip install -e .
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1

      - name: Run tests
        id: run-tests
        run: |
          python -m pytest tests/ -v --cov=plainspeak --cov-report=term-missing
        continue-on-error: true
      
      - name: Create test report
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "Version: ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
          
          # Get test exit code from previous step
          if [ "${{ steps.run-tests.outcome }}" = "success" ]; then
            echo "✅ Tests passed successfully" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Some tests failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "See above for detailed test output and coverage report." >> $GITHUB_STEP_SUMMARY
