name: Package Test Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to test'
        required: true
        default: '0.1.0-test'

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.version }}
  cancel-in-progress: true

jobs:
  test-package:
    name: Test Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements-tests.txt
          pip install -e .
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1

      - name: Run tests
        id: run-tests
        run: |
          # Run tests and capture output
          python -m pytest tests/ -v --cov=plainspeak --cov-report=term-missing 2>&1 | tee test_output.log
          
          # Store exit code
          echo "exit_code=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT
        continue-on-error: true
      
      - name: Create test report
        if: always()
        run: |
          {
            echo "## Test Results"
            echo "Version: ${{ github.event.inputs.version }}"
            echo ""
            
            if [ "${{ steps.run-tests.outputs.exit_code }}" = "0" ]; then
              echo "✅ Tests passed successfully"
            else
              echo "❌ Some tests failed"
            fi
            
            echo ""
            echo "### Detailed Test Output"
            echo "\`\`\`"
            cat test_output.log
            echo "\`\`\`"
            
          } >> $GITHUB_STEP_SUMMARY
