name: Generate Assets

on:
  push:
    paths:
      - 'assets/icons/source/**'
      - 'scripts/generate_assets.py'
      - '.github/workflows/generate-assets.yml'
  pull_request:
    paths:
      - 'assets/icons/source/**'
      - 'scripts/generate_assets.py'
      - '.github/workflows/generate-assets.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate:
    name: Generate Assets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements-assets.txt

      - name: Generate assets
        run: python scripts/generate_assets.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update generated assets'
          title: 'chore: update generated assets'
          body: |
            This PR updates the generated assets based on changes to source files.
            
            Changes were automatically generated by the `generate-assets.yml` workflow.
            
            Please review the generated assets to ensure they meet quality standards.
          branch: update-generated-assets
          base: main
          labels: |
            assets
            automated-pr
          delete-branch: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-assets
          path: |
            assets/icons/windows/
            assets/icons/macos/
            assets/store/
          if-no-files-found: error

      # Optional: Validate generated assets
      - name: Validate assets
        run: |
          # Check if all required files exist
          for size in 16 32 48 256; do
            test -f "assets/icons/windows/icon-$size.png" || exit 1
          done
          test -f "assets/icons/windows/plainspeak.ico" || exit 1
          
          for size in 16 32 128 256 512 1024; do
            test -f "assets/icons/macos/icon-$size.png" || exit 1
          done
          
          test -f "assets/store/apple/app-store-icon.png" || exit 1
          
          for size in 44 71 150 310; do
            test -f "assets/store/microsoft/store-$size.png" || exit 1
          done
          
          # Check file permissions
          find assets/icons assets/store -type f -exec test -r {} \; || exit 1
          
          # Verify image formats
          for f in $(find assets/icons assets/store -name "*.png"); do
            file "$f" | grep -q "PNG image data" || exit 1
          done
          
          echo "All assets validated successfully"
